### ISSUE TITLE
Consider whether erfapy is a better name

### ISSUE THREAD

**Issue by eteq** [liberfa/pyerfa#1]
`pyerfa` seems like a natural name given `liberfa`, but with a bit of thought,  I think I slightly prefer the name `erfapy` over `pyerfa`, because there's a lot of `py<something>` packages.  I can rename the repo easily enough but of course we'd also need to update references to it in the code itself.  What do you think, @mhvk or @avalentino

**Comment by avalentino** [comment]
Sorry I'm not the right person to ask this kind of things, I have chosen horrible names in the past :)

**Comment by astrofrog** [comment]
> because there's a lot of py<something> packages

I mean... you may have picked the wrong programming language if that bugs you 😆 I don't really have a strong preference either way, and I find 'pyerfa' to flow more nicely when said out loud, so you can count this as a +0.25 for pyerfa :wink:

**Comment by mhvk** [comment]
To me, `pyerfa` seems slightly better - I associate `*py` with whole python packages "num(erical)py(thon)", "sci(entific)py(thon)", "astro(nomy)py(thon)", etc., while `py<something>` to me suggests "python version of something" as in `pyfftw`. But I'm sure many counterexamples can be found.... (eg., `h5py`, `mpi4py`...).
Anyway, another +0.5 for `pyerfa`...

**Comment by eteq** [comment]
Hmm. well now that's awkward since I think I'm sort of +0.75 for `erfapy`.  But in the event of I tie I guess that means we leave status quo unless more opinions appear :wink:

**Comment by eteq** [comment]
Although... does pypi and pip support unicode?  We could go with  `🥧erfa`...

**Comment by mhvk** [comment]
well, if so, I vote for erfa:snake:

**Comment by mhvk** [comment]
I think we're going with `pyerfa`
