### ISSUE TITLE
Documentation from C functions should not be coloured

### ISSUE THREAD

**Issue by mhvk** [liberfa/pyerfa#10]
Right now, the C function docstring is typeset as fixed width, but still coloured as if it is python:

![image](https://user-images.githubusercontent.com/2789820/81228201-9d5d1180-8fbb-11ea-887b-f72d11a1cfce.png)

**Comment by avalentino** [comment]
This should be fixed in #15 (conf.py [L68](/avalentino/pyerfa/blob/5fe9761bab1d92753622946227e5c85450ed545f/docs/conf.py#L67))
