### ISSUE TITLE
Package creation should ensure core.py and ufunc.c are up to date

### ISSUE THREAD

**Issue by mhvk** [liberfa/pyerfa#11]
The auto-generated `core.py` and `ufunc.c` should be up to date with their templates before a package is created. At least in one occasion, `tox -e build_docs` created pages that did not have an update propagated through.

**Comment by astrofrog** [comment]
I think this is related:

https://github.com/liberfa/pyerfa/pull/5#issuecomment-624891275

Basically we should generate files on all ``setup.py`` invocations, never skipping even if files already exist.

**Comment by mhvk** [comment]
Thanks, that sounds right! Of course, in astropy we didn't generate documentation, so this wouldn't have come up.

**Comment by mhvk** [comment]
@astrofrog - more as an aside, while looking at `astropy/_erfa/setup_package.py`, I encountered [`GEN_FILES`](https://github.com/astropy/astropy/blob/441486c8cf1d80409520ea756cf006932cb57c77/astropy/_erfa/setup_package.py#L22-L23): I think this is just a leftover that can be safely removed there, or does it have meaning for packaging, that items listed in there get checked/skipped?

**Comment by mhvk** [comment]
I think part of what tricked here was that the files are in `.gitignore`, so for packaging it works if one cleans beforehand. Also, in astropy we do generally include *.c files in the manifest, but I think this aims at source code, not generated code. Anyway, overall it seems logical to always generate, so trying that in #13.
