### ISSUE TITLE
Need new bug-fix release once numpy 2.0 is out

### ISSUE THREAD

**Issue by mhvk** [liberfa/pyerfa#138]
Numpy 2.0 is imminent, but our released versions are not compatible with it, so we need a bugfix release once it is out (maybe even once the RC is out, since nothing much should change after).

**Comment by neutrinoceros** [comment]
My understanding is that we *should* indeed wait for a release candidate for guaranteed ABI compatibility.

**Comment by mhvk** [comment]
Yes, you're right, we should release on the first release candidate. Indeed, for `erfa`, it is extremely unlikely that anything will still change after, so we probably can even release on beta rather than rc1.

**Comment by pllim** [comment]
I think we need this now. Downstream sees error when trying to test astropy v6.1rc with numpy 2.0rc. Can someone please push a RC out for pyerfa too? Thanks!

cc @braingram

**Comment by mhvk** [comment]
Sure, I'll make a point release - hopefully, the macos wheels would be fixed in the meantime.

**Comment by braingram** [comment]
Thanks for the quick response.

However, I am seeing numpy version errors with pyerfa 2.0.1.2:
https://github.com/astropy/asdf-astropy/actions/runs/8559737645/job/23457158004?pr=224#step:10:47
that I did not see with the "nightly" version:
https://github.com/astropy/asdf-astropy/actions/runs/8559342737/job/23455932848#step:10:60

Does the `pyproject.toml` need a version requirement for numpy?
https://github.com/liberfa/pyerfa/blob/ed48e7e6217f3b10cf08ebdfdb023f117378ff06/pyproject.toml#L6

**Comment by mhvk** [comment]
Darn, I worried I should have tested further. I thought #143 by @neutrinoceros had ensured that we build all our wheels with numpy rc. I'll investigate.

**Comment by mhvk** [comment]
Ah, I think I see that that was only for PRs...

**Comment by mhvk** [comment]
I think we need #144 before the release. I'm reopening this. Note that I've run out of time here, and am away over the weekend to see the eclipse, so unless someone else takes over, this likely will have to wait until after (April 9th).

**Comment by pllim** [comment]
Looks like 2.0.1.2 also broke devdeps on `astropy` CI -- https://github.com/astropy/astropy/actions/runs/8561665489/job/23463362225

It is not picking up nightly wheel anymore. But even if it does, looks like nightly wheel build is broken https://github.com/liberfa/pyerfa/actions/workflows/publish.yml?query=event%3Aschedule

**Comment by neutrinoceros** [comment]
Maybe @astrofrog or @avalentino could yank this broken release ?

**Comment by astrofrog** [comment]
Will do once I get to my desk

**Comment by Schamschula** [comment]
Please don't require betas or release candidates. As the MacPorts port maintainer of py-pyerfa, I have to hold back updating to 2.0.1.3, as we don't have a py-numpy-devel port tracking the 2.0.0rc releases.

**Comment by astrofrog** [comment]
@Schamschula - unfortunately this is the recommendation of the Numpy developers:

https://github.com/numpy/numpy/issues/24300#issuecomment-2030603395

we need to get wheels compatible with Numpy 2.0 out before Numpy 2.0 is released. However, it's fine to just wait until Numpy 2.0 final is out to update MacPorts, it shouldn't take too long and there are no critical changes in 2.0.1.3 that mean updating in MacPorts is urgent.

**Comment by astrofrog** [comment]
Closing this as PyERFA 2.0.1.3 is released, built against Numpy 2.0.0rc1

**Comment by mhvk** [comment]
Thanks @astrofrog and @neutrinoceros, and apologies for messing up 2.0.1.2.

**Comment by neutrinoceros** [comment]
happens to the best of us :)
