### ISSUE TITLE
Fix up "fork" status if needed

### ISSUE THREAD

**Issue by eteq** [liberfa/pyerfa#2]
I populated the initial master branch of this repo by pushing from https://github.com/avalentino/pyerfa/tree/pyerfa-standalone .  That made sense at the time as a way to keep only the pyerfa part, but as a result neither one appears as a "fork" of the other.  Maybe that's fine, but @avalentino, I thought I'd check to see if you care. I think there's a few options:

1. Start over and have `liberfa/pyerfa` be a fork of `avalentino/pyerfa`
2. Delete `avalentino/pyerfa` and replace it with a fork
3. If we switch to `erfapy` in #1, it's easy enough to have a separate `avalentino/erfapy` fork
4. Send a github support request for them to set up the "fork" status (I have a hazy memory that they'll do this if you have a reason).

Any could work, but I think I prefer either 3 or 4, or just leaving things as they stand.

**Comment by avalentino** [comment]
Hi @eteq thank you for creating this repository.
I'm perfectly fine with repository as it is now, the fork status is not important for me.
Thank you for asking but for me you can just close this issue.

**Comment by mhvk** [comment]
I think this `liberfa` one should be the "non-fork", which I think is right. Since @avalentino agrees, I'll close this. Thanks, @eteq!
