### ISSUE TITLE
Set up authors?

### ISSUE THREAD

**Issue by mhvk** [liberfa/pyerfa#21]
We could leave authors as "the astropy developers", or should it go to be more erfa specific? From `git shortlog`, I'd infer that the contributors are (alphabetical):
- Antonio Valentino
- Erik Tollerud
- Julien Woillez
- Marten van Kerkwijk
- Michael Droettboom
- Thomas Robitaille

And maybe
- Erik M. Bray(?)
- Stuart Littlefair(?)

**Comment by astrofrog** [comment]
I'm happy to be left out. We could also make it 'The ERFA developers'

**Comment by mhvk** [comment]
I was about to just add the names, when I saw in `setup.cfg` that there is also an "author e-mail" - is there perhaps a way to write to all maintainers at the same time? Or should we start a mailing list? Or just suggest to raise an issue?

**Comment by avalentino** [comment]
Probably an docs/credits.rst file (like in astropy) would be simler so we can use "The ERFA developers".

Regarding the author-email field I think it is not mandatory, we could just drop it.
