### ISSUE TITLE
Set up pyerfa on conda-forge

### ISSUE THREAD

**Issue by astrofrog** [liberfa/pyerfa#36]
It would be good to set up pyerfa on conda-forge soon now that there is a stable release of pyerfa - this will then give time to iron out any issues and allow us to ask for it to be included in the defaults conda channel ahead of the next major astropy release (meaning v4.2).

@mwcraig - is this something you have time to help with? (setting up the conda recipe)

**Comment by mwcraig** [comment]
sure, no problem. I'm no longer sure who to contact an anaconda -- maybe Kale Franz? Also, what is your preferred c-f maintainer user name @astrofrog?

**Comment by astrofrog** [comment]
I'll try and dig up who to contact at anaconda - maybe for now we can just get it on to conda-forge. And for conda forge, my username is @astrofrog-conda-forge

**Comment by mwcraig** [comment]
PR opened: https://github.com/conda-forge/staged-recipes/pull/11796

**Comment by astrofrog** [comment]
Thanks @mwcraig!

**Comment by mwcraig** [comment]
That PR has been merged, so I think this should be closed. I'll add pyerfa to the astropy channel list shortly; it takes about 24 hours to auto-update, I think.

**Comment by mwcraig** [comment]
Just confirmed that this is on the conda-forge channel now and has been copied to astropy.

**Comment by astrofrog** [comment]
Thanks!
