### ISSUE TITLE
Need to be on default conda channel before astropy 4.2 is released

### ISSUE THREAD

**Issue by pllim** [liberfa/pyerfa#42]
`astropy` is shipped to conda default channel. Given that `astropy` 4.2 and later would require this package, it would be desirable for this package also be in conda default channel. Otherwise, it might break `astropy` in conda default channel.

See discussions at https://github.com/astropy/ci-helpers/pull/451#issuecomment-656452565 . xref astropy/astropy#10329

When this is done, please either open an issue, or better yet, a pull request, to let `ci-helpers` grab `pyerfa` from `conda` too, instead of `pip` (especially for Appveyor). However, this would be moot if we retire `ci-helpers` before this happens (which is very unlikely).

p.s. See https://github.com/astropy/astropy/wiki/Release-Calendar for astropy release timeline.

cc @mwcraig and @bsipocz

**Comment by bsipocz** [comment]
I foresee it will go in there at the same time, quasi automatically as it's listed as a dependency in the recipe. (same way as pytest-astropy ended up there).

**Comment by mhvk** [comment]
Closing since astropy 4.2 was released a long time. If there is a worry for pyerfa 1.7.3 and astropy 4.3, do open a new issue!
