### ISSUE TITLE
ErfaWarning message has changed

### ISSUE THREAD

**Issue by StuartLittlefair** [liberfa/pyerfa#48]
Thanks to https://github.com/liberfa/pyerfa/commit/00c3334bc2c41bc7bbaedd6afdc02dad357d2c7e the warning message for an ErfaWarning has changed from e.g.

```
ERFA function "pmsafe" yielded 1 of "distance overridden (Note 6)"
```

to

```
ERFA function 'pmsafe' yielded 1 of "distance overridden (Note 6)"
```

Note the change in quotation around the function name. This change is causing upstream issues in astropy testing - see https://github.com/astropy/astropy/issues/10648 for details

**Comment by mhvk** [comment]
Oh, darn, I didn't even see that you had a PR ready to fix this, and blatantly went ahead my own, #50. Sorry!
