### ISSUE TITLE
Port thread safety improvement to classproperty from astropy

### ISSUE THREAD

**Issue by bmerry** [liberfa/pyerfa#63]
astropy/astropy#11221 fixes a race condition when multiple threads read a lazy `classproperty`. It looks like `classproperty` has been copied into pyerfa, so the fix should be ported (once it is merged in astropy).

**Comment by bmerry** [comment]
Thanks @mhvk, you beat me to it!

**Comment by mhvk** [comment]
No, thanks to you for realizing we used the `classproperty` here too!

**Comment by bmerry** [comment]
It was pure luck: I was digging into pyerfa while investigating leap-seconds and happened across some familiar-looking code :-)
