### ISSUE TITLE
Need to set up version

### ISSUE THREAD

**Issue by mhvk** [liberfa/pyerfa#7]
Likely not the only thing, but needs a bit of thought on numbering: we could simply stick to the `erfa` version, but that means that if there is a bug in the python wrapper, we would need to deviate.

@avalentino, @astrofrog, @eteq - any suggestions? I guess we could let the bug-fix part deviate from `erfa` itself.

EDIT: for the post-fix, we can use the version-getting function from https://github.com/liberfa/pyerfa/pull/28#issuecomment-626300892

**Comment by astrofrog** [comment]
Could we also add a fourth version number, so say ERFA is on 3.2.1, we could then have pyerfa 3.2.1, 3.2.1.1, 3.2.1.2, etc?

**Comment by mhvk** [comment]
Yes, I like that fourth-number scheme!

**Comment by avalentino** [comment]
+1 for the fourth-number scheme

**Comment by mhvk** [comment]
Probably should at least think through the alternatives:
1. Separate version number altogether.
2. Start with `PyERFA` number and append `liberfa` (perhaps `1.1.7.0` or `1.0-1.7.0`).
Since we use the submodule, a combination seems somewhat more logical.

**Comment by avalentino** [comment]
> Probably should at least think through the alternatives:
>
> 1. Separate version number altogether.
> 2. Start with PyERFA number and append liberfa (perhaps 1.1.7.0 or 1.0-1.7.0).
>    Since we use the submodule, a combination seems somewhat more logical.

IMHO (1.) is also a good option as soon as we document which is the liberfa version we bundle in each release. (2.) honestly I prefer postfix version proposed by @astrofrog , also the `1.0-1.7.0` variant could be very tricky to manage.

**Comment by mhvk** [comment]
Another thought: generally, the python wrappers will/*should* work perfectly well with any `liberfa` of a given release, independent of the bug-fix number. I.e., say, `pyerfa-1.7.0` would/should work with `liberfa-1.7.1` and vice versa. So, the scheme could also be that we keep the bugfix number for `pyerfa` separate from that of `liberfa`.

Alternatively, in the `pyerfa` version, the erfa version part could simply be the *minimal* `liberfa` bugfix version it supports. Perhaps that makes more sense, since the C code that is bundled will be that minimal version, so the wrappers will work for that and simply ignore, say, any new C functions.

**Comment by avalentino** [comment]
The first option could be interesting mostly considering that as far as I can understand it is unlikely that liberfa will ever have a patch version different form zero, and also in that case the corresponding action on the pyerfa side will probably be just to make a patch release with updated liberfa sources.

The second option could result in some confusion for the user IMHO. I agree with you that the same pyerfa version can support multiple liberfa versions but:
* the main user endpoint will probably be the package n pypi which also included liberfa sources so it would be strange to have pyerfa 1.7.2 which bundles e.g liberfa 1.9.0
* in that case it would be probably better to use a totally independent versioning and update the minimum supported liberfa version in the release notes

**Comment by avalentino** [comment]
@astrofrog  @mhvk we should make a decision on this to move forward.
Since we decided to bundle liberfa sources IMHO the versioning option that uses the same liberfa version + an optional fourth number seems to be the one that makes more sense.

If you agree I will go on and merge PR #30

**Comment by astrofrog** [comment]
No strong opinions here, but I agree that the idea of keeping the bugfix number separate could make a lot of sense, but I'm also ok with the fourth number approach. To be completely honest, for *most* users this won't matter.

**Comment by avalentino** [comment]
Thanks @astrofrog the solution that keeps the bugfix number separate is the easiest one, it is basically already implemented :). I'm also fine with it.
@mhvk which is your preferred solution?

**Comment by mhvk** [comment]
OK, I think in the end we should just go with the match-liberfa version and keep a possible fourth digit for fixes to the python wrappers.  As noted, really users won't care and this is implemented. I now made a last fix to #30 which should implement that.

**Comment by avalentino** [comment]
OK, thanks @mhvk

**Comment by mhvk** [comment]
fixed by #30
