### ISSUE TITLE
New minor release?

### ISSUE THREAD

**Issue by astrofrog** [liberfa/pyerfa#79]
Would it be possible to do a new minor release of pyerfa? @Cadair added a set of new wheel architectures in #78 but these will only actually be built when a new release is done, and it would be nice to have this in time for the upcoming 5.0 release of core astropy. Thanks!

**Comment by astrofrog** [comment]
@mhvk @avalentino - just to check, is this something you might have time to do this week? Thanks!

**Comment by mhvk** [comment]
Yes, makes sense to do a minor release. I should be able to do that today or tomorrow. That will then be 2.0.0.1...

**Comment by mhvk** [comment]
OK, 2.0.0.1 is released!

**Comment by Cadair** [comment]
That's a lot of `.0`s! :wink: 

Thanks for the release!

**Comment by Cadair** [comment]
And it fixed the [astropy builds](https://dev.azure.com/astropy-project/astropy/_build/results?buildId=2458&view=results) :partying_face:

**Comment by mhvk** [comment]
Hurray!!!
