### ISSUE TITLE
Consider using Azure pipelines template for auto-releasing package

### ISSUE THREAD

**Issue by astrofrog** [liberfa/pyerfa#8]
@Cadair and I have created an Azure pipelines template for auto-releasing Python packages, including wheels for all the different platforms:

https://openastronomy-azure-pipelines.readthedocs.io/en/latest/

With this, pushing a tag to GitHub results in the release happening automatically. Since this is a new project, it might be worth setting this up here. An alternative would be to figure out how to do this as a GitHub action, but that would require more work for now. I do want to try and do this at some point, but if we wanted something soon we could start with the Azure pipelines version.

I'd be happy to set this up if others are interested. I use this for reproject and sunpy use it for the main sunpy package, and it works great. I also want us to use something like this for the core package in the long term.

**Comment by astrofrog** [comment]
If there is interest in this I might also investigate using GitHub actions with cibuildwheel directly (as this was recently implemented in https://github.com/joerick/cibuildwheel/pull/194)

**Comment by avalentino** [comment]
It is a good idea IMHO.
If you already use Azure pipelines we could go with it.

**Comment by mhvk** [comment]
Yes, `pyerfa` seems like a very good candidate, since for most releases there will (presumably) be very little to do beyond updating the submodule to a new version!

Since I have little clue about this so far, I'll leave it to you to pick the preferred route.

**Comment by astrofrog** [comment]
I can set it up with Azure for now, but with the understanding we can switch to e.g. GitHub actions if we want at some point. The Azure template works at the moment, so path of least resistance.
