### ISSUE TITLE
Try to switch to a non-distutils/setuptools extension build system

### ISSUE THREAD

**Issue by eteq** [liberfa/pyerfa#91]
Distutils is going away (https://peps.python.org/pep-0632/ ), setuptools has a questionable future without `distutils` in the stdlib, and perhaps most relevantly, as a result it seems a lot of the scientific python ecosystem (e.g. scipy and numpy) are moving to other build systems for c extensions.  So I think we need to consider whether we should/will need to switch to one of the build systems those packages are using.

I think the main options are [meson](https://mesonbuild.com/), [scikit-build](https://scikit-build.readthedocs.io/en/latest/) (which is build on cmake) or [CMake](https://cmake.org/) directly. Based purely on trying to not fracture the ecosystem, I'm inclined to look into meson, since that's the way scipy has gone, and the rumor at least I hear is that numpy is thinking that way too (@rgommers might have some insight or thoughts to add on that).

**Comment by rgommers** [comment]
@eteq indeed, NumPy and Pandas will move to Meson as well. Scikit-learn is going to stick with `setuptools` for a while (just moving away from `numpy.distutils`) until they're more confident that Meson is stable and a significant improvement. 

I've been very happy with Meson so far, it's a huge improvement. SciPy has been building with Meson in `main` and in CI since Dec'21, with very few issues. The one thing that is less mature right now is building wheels with `meson-python`. They're not major issues, but we do still need several fixes for wheel platform and ABI tags; all known issues should be resolved in `meson` 0.64.0 (expected second half of Oct) and more importantly `meson-python` 0.9.0 (hopefully next week).

You could add Meson build support now, and wait with switching the PEP 517 hook in `pyproject.toml` until those releases are out.

**Comment by eli-schwartz** [comment]
A good starting point would be to switch the submodule "erfa" dependency to Meson. https://github.com/liberfa/erfa/pull/90

**Comment by mhvk** [comment]
@eli-schwartz - that plan sounds good. I like the clarity of the `meson.build` files in https://github.com/liberfa/erfa/pull/90. I'm sure the various distributions would appreciate that system libraries are used automatically! (cc @sergiopasra, @olebole in case).

**Comment by mhvk** [comment]
Just to note that the prequel, of building `erfa` itself with `meson` looks good and is as far as I can see ready for merging - @eteq, @sergiopasra, @olebole - please have a look! https://github.com/liberfa/erfa/pull/90

**Comment by olebole** [comment]
I have no experience with Meson so far, so I can't really contribute here much. There is a Debian package for Meson, so I would think that I will be able to build.
What I could do is to try to build a Debian package based on https://github.com/liberfa/erfa/pull/90 and see if I run into difficulties; however this may take a few days.

**Comment by mhvk** [comment]
@olebole - thanks! I can certainly confirm that things work on Debian (since I run it). And of course CI runs on Ubuntu. So, presumably packaging will be easy too.

Anyway, as is the suggestion is to keep the autotools versions in parallel until after the next release.

**Comment by olebole** [comment]
Then you can just proceed; I will come back to you if I have problems understanding Meson :-)

**Comment by eli-schwartz** [comment]
> What I could do is to try to build a Debian package based on [liberfa/erfa#90](https://github.com/liberfa/erfa/pull/90) and see if I run into difficulties; however this may take a few days.

Debian has pretty good support for Meson in debhelper, so this may be as simple as passing --buildsystem=meson to all `dh*` commands if it notices both configure and meson and tries to use autotools by default, and adding Meson as a build dependency.

**Comment by olebole** [comment]
Thanks, I'll try!

**Comment by mhvk** [comment]
We moved to `meson` to build `pyerfa`, and we haven't heard any complaints about it since, so closing this issue.

**Comment by eerovaher** [comment]
> We moved to `meson` to build `pyerfa`

Then why does `pyproject.toml` say https://github.com/liberfa/pyerfa/blob/1a6e9da52f7123f8f8a03ae36a5f7a4c053f93e7/pyproject.toml#L7
