### ISSUE TITLE
Trigger a new release to build Python 3.11 wheels?

### ISSUE THREAD

**Issue by astrofrog** [liberfa/pyerfa#93]
Now that Python 3.11 is out, we should make a new release of PyERFA so that the Python 3.11 wheels get built.

**Comment by neutrinoceros** [comment]
+1 to this. Having to compile from source adds about a minute of overhead on `pip install astropy`

**Comment by mworion** [comment]
+1 really need this as users mostly not able to build themself (amateur astronomers are no programmers)
